### ISSUE TITLE
PNMLにて空のトランジションに#でコメントを付けるとルールとして変換されます

### ISSUE THREAD

**Issue by kinoshita-eos** [pione/pione#60]
木下です。

PNML記法仕様書.odtの7ページ目にて「コメント記法」として「#以降の文字列はコメントとして見做して無視する」とありますが、こちらは現在の仕様では変更となっているのでしょうか。

試してみましたが、コメント扱いになりませんでした。

pnmlファイル
![2015-01-08 17 10 33](https://cloud.githubusercontent.com/assets/9475777/5659662/512449a6-9759-11e4-9098-97f02cbfac02.png)

mdファイル
```
# test.pione

## First
Test.

```　
echo "Hello World!" > {$O[1]}
```　
```

変換された定義書
```
Rule Main
  output '*.txt'
Flow
  rule First
  rule #Comment
End

Rule First
  output 'message.txt'
Action
  echo "Hello World!" > {$O[1]}
End

Rule #Comment
  input 'message.txt'
  output ('*.txt').touch
End
```
上記のように#Commetがルールとして作成されてしまいます。

**Comment by keita** [comment]
>PNML記法仕様書.odtの7ページ目にて「コメント記法」として「#以降の文字列はコメントとして見做して無視する」とありますが、こちらは現在の仕様では変更となっているのでしょうか。

仕様上コメントです。が、0.4.2ではコメントがうまく機能しないケースが多いです。これはパーサがPIONE言語のものと異なる暫定的なものを使用している為です。

これについては次のリリースでPIONE言語のパーサを使用するように変更されるので解決されます。試す場合にはブランチ0.5.0もしくはプレリリース版のgem（gem install --pre）を使用して下さい。

**Comment by kinoshita-eos** [comment]
木下です。

回答ありがとうございます。
理解しました。
