### ISSUE TITLE
IntやFloatの四則演算の件

### ISSUE THREAD

**Issue by kinoshita-eos** [pione/pione#62]
木下です。

PIONE一覧.odtにて6 - 8ページ目のInt型、Float型にて四則演算子(+, -, *, /)について質問よろしいでしょうか。

これらは恐らく二項演算子で基本的には同じ型に対して"$val1 + $val2"のように使用すると思います。
括弧を付けずに三項以上で使用した場合は右から解釈されるようです。

```
$ pione val "2*3+4"
14
$ pione val "(2*3)+4"
10
```

「三項以上の場合は括弧を使用して、必ず二項ずつの演算にする」使用の仕方をすると考えてよろしいでしょうか。

**Comment by keita** [comment]
>括弧を付けずに三項以上で使用した場合は右から解釈されるようです。

これは現在の実装における制限です。言語的には四則演算は常識的な順序で処理する事になります。

>「三項以上の場合は括弧を使用して、必ず二項ずつの演算にする」使用の仕方をすると考えてよろしいでしょうか。

従って、これは現在の実装としてはその通りですが、将来的には修正されます。この為、現時点では必ず括弧で括るようにお願いいたします。

**Comment by kinoshita-eos** [comment]
木下です。

回答ありがとうございました。

もう一点確認なのですが、現在の演算では同じ型のみに対しての演算は定義されていますが、異なる型についての演算は今後は定義されないのでしょうか。(1+1.0などは必ず1.f()+1.0にする？)

**Comment by keita** [comment]
>もう一点確認なのですが、現在の演算では同じ型のみに対しての演算は定義されていますが、異なる型についての演算は今後は定義されないのでしょうか。(1+1.0などは必ず1.f()+1.0にする？)

現時点では型変換は明示的に行う方針で考えていますので、1.f()+1.0の書き方でお願い致します。

**Comment by kinoshita-eos** [comment]
木下です。

回答ありがとうございます。
全て解決しましたので、こちらでクローズさせて頂きます。
