### ISSUE TITLE
OddSelector.pioneの件

### ISSUE THREAD

**Issue by kinoshita-eos** [pione/pione#63]
木下です。

OddSelector.pioneにて使用しているメソッドにて２点ほどよろしいでしょうか。

(7行目) rule OddFilter >>> MakeResult

　>>>はメソッド一覧.odt(8ページ目)にて
レシーバと第１引数を無名のチケットに結合した結果をシーケンスに結合して返却する。

とありますが、こちらは
OddFilterを実行後にMakeResultを実行するような内容ということでしょうか。

用途として
rule OddFilter
rule MakeResult
とすると、先にMakeResultが実行される場合があるので、
順番を決めたいときにrule OddFilter >>> MakeResultを使うのでしょうか。

(13行目) constraint ($I[1][1].i % 2) == 0

constraint以降の条件を発火条件に加えるものと考えてよろしいでしょうか。

**Comment by keita** [comment]
>OddFilterを実行後にMakeResultを実行するような内容ということでしょうか。

その通りです。チケットは強制的な順序を指定するのに使用します。同じ内容は

```
rule OddFilter ==> <T>
rule <T> ==> MakeResult
```

とする事でも記述できます。

>先にMakeResultが実行される場合があるので、
>順番を決めたいときにrule OddFilter >>> MakeResultを使うのでしょうか。

その通りですが、より正確には同時実行を防ぐ場合にも使用します。

>constraint以降の条件を発火条件に加えるものと考えてよろしいでしょうか。

こちらはまさにその通りになります。constraint宣言子は制約条件文を設定します。

**Comment by kinoshita-eos** [comment]
木下です。

回答ありがとうございました。
全て解決しましたので、こちらでCloseさせて頂きます。
