### ISSUE TITLE
ブロックコメントの件

### ISSUE THREAD

**Issue by kinoshita-eos** [pione/pione#65]
木下です。

単純な質問ですが、PIONEにてブロックコメントを加える記法はありますでしょうか。Actionの中ではシェルスクリプトでのブロックコメントを加えていますが、FlowやRuleの一部では#で各行をコメントアウトしております。何か良い方法をご存知でしたら教えて頂けないでしょうか。

**Comment by keita** [comment]
>単純な質問ですが、PIONEにてブロックコメントを加える記法はありますでしょうか。

すみません、ブロックコメントは存在しません。コメント記法が「#」の言語ですのであまりブロックコメントは良い記法が思いつかないので、おそらく範囲をコメントアウトしてくれるようなelispを書くのが良いのかと思いますが、いかがでしょうか？

**Comment by kinoshita-eos** [comment]
木下です。

回答ありがとうございます。
ブロックコメントは設定されていないことを理解しました。何か工夫できるか考えてみます。
解決しましたので、こちらの方でCloseさせて頂きます。
