### ISSUE TITLE
【質問】ルールのパラメータにシーケンスを代入したとき

### ISSUE THREAD

**Issue by kinoshita-eos** [pione/pione#67]
木下です。

ルール内に定義されているパラメータにシーケンスを代入したときについて確認よろしいでしょうか。

例えば、下記にてvalの値によるファイルを作成する定義書にて

```
Rule Main
    output '{$val}.txt'
    param $val := 0
Action
    touch {$O[1]}
End
```

デフォルトでは0.txtが作成されますが、これを

```
$ pione-client test.pione --params='{val:(1|2)}'
```

というようにすると、Mainが２回動いて、1.txtと2.txtが作成されます。

パラメータにシーケンスを代入したときは各々のデータについてルールが発火すると考えてよろしいでしょうか。
uptoなどを用いてfor文の代用ができ、非常に便利だと思い、確認させて頂いた次第です。

**Comment by keita** [comment]
> パラメータにシーケンスを代入したときは各々のデータについてルールが発火すると考えてよろしいでしょうか。
> uptoなどを用いてfor文の代用ができ、非常に便利だと思い、確認させて頂いた次第です。

ご指摘の使い方を意図してデザインされた言語体系ですので、問題ありません。PIONE言語は組み合わせ生成を容易に生成出来るようにしていますが、これは同一フローをデータやパラメータを様々に変更しながら試していく事が目的です。

**Comment by kinoshita-eos** [comment]
木下です。

回答ありがとうございました。
理解しました。
他にも便利な使い方があるかを考えながら定義書を作成しようと思います。
