### ISSUE TITLE
Booleanメソッドone?の件

### ISSUE THREAD

**Issue by kinoshita-eos** [pione/pione#68]
木下です。

Booleanメソッドone?について質問よろしいでしょうか。

「PIONEメソッド一覧.odt」(4ページ)より、

```
レシーバの要素数が1であり、その要素がtrueであればtrueを返却する。
```

とあります。

要素数が1でない場合はどんな結果が期待されるのでしょうか。
現在の動作では下記のようになっています。

```
$ pione val '(true|false).one?()'
true
$ pione val '(false|true).one?()'
true
$ pione val '(false|false).one?()'
false
```

**Comment by keita** [comment]
> レシーバの要素数が1であり、その要素がtrueであればtrueを返却する。
> 要素数が1でない場合はどんな結果が期待されるのでしょうか。

これは説明文が間違っております。#one?はレシーバにtrueが一つだけ存在する場合にtrueを返却します。後ほどメソッド一覧を修正します。

**Comment by kinoshita-eos** [comment]
木下です。

回答ありがとうございました。

```
$ pione val '(true|true).one?'
false
```

上記にて1つtrueがあった場合は確かにfalseが返ってきました。
内容理解しました。
