### ISSUE TITLE
【質問】Stringメソッドjoinにて引数なしのとき

### ISSUE THREAD

**Issue by kinoshita-eos** [pione/pione#69]
木下です。

Stringメソッドjoinについて質問よろしいでしょうか。
「メソッド一覧.odt」(5ページ)により、

引数がある場合は、引数で指定した文字列で結合した文字列を返すとのことなので、
下記のように動作することは理解しました。

```
$ pione val '("a"|"b"|"c").join("-")'
a-b-c
```

引数がない場合は、「結合した文字列を返却する」とあり、
下記のようになります。

```
$ pione val '("a"|"b"|"c").join()'
a b c
```

引数がない場合は空白を結合部分として結合する動作となっているのでしょうか。
（.join(" ")と同じ？）

**Comment by keita** [comment]
> 引数がない場合は空白を結合部分として結合する動作となっているのでしょうか。
> （.join(" ")と同じ？）

ご指摘の通り指定のない場合は空白で結合します。これはシェルスクリプトに結果を埋め込む場合に、どのような形で埋め込まれるのが最適かを検討した結果、このようになりました。

**Comment by kinoshita-eos** [comment]
木下です。

回答ありがとうございます。

なるほど、ファイル名などをまとめて設定したいときなどに便利そうです。
解決しました。
